//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyDreamFoam_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Empleado()
        {
            this.Tb_Diario = new HashSet<Tb_Diario>();
            this.Tb_Marcas = new HashSet<Tb_Marcas>();
        }
    
        public int codEmpleado { get; set; }
        public string numroDoc { get; set; }
        public string tipoDoc { get; set; }
        public string apellidos { get; set; }
        public string nombres { get; set; }
        public System.DateTime fecNacimiento { get; set; }
        public string genero { get; set; }
        public string correo { get; set; }
        public string direccion { get; set; }
        public Nullable<int> telefono { get; set; }
        public System.DateTime fecIngreso { get; set; }
        public int codCargo { get; set; }
        public int codArea { get; set; }
        public int codSede { get; set; }
        public int codHorario { get; set; }
        public byte[] foto { get; set; }
        public Nullable<System.DateTime> fec_Reg { get; set; }
        public string usu_Reg { get; set; }
        public Nullable<System.DateTime> fec_UltMod { get; set; }
        public string usu_UltMod { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual Tb_Area Tb_Area { get; set; }
        public virtual Tb_Cargo Tb_Cargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Diario> Tb_Diario { get; set; }
        public virtual Tb_Documento Tb_Documento { get; set; }
        public virtual Tb_Horario Tb_Horario { get; set; }
        public virtual Tb_Sede Tb_Sede { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Marcas> Tb_Marcas { get; set; }
    }
}
