//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyDreamFoam_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Horario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Horario()
        {
            this.Tb_Empleado = new HashSet<Tb_Empleado>();
        }
    
        public int codHorario { get; set; }
        public string desHorario { get; set; }
        public Nullable<System.TimeSpan> ingLUN { get; set; }
        public Nullable<System.TimeSpan> salLUN { get; set; }
        public Nullable<System.TimeSpan> ingMAR { get; set; }
        public Nullable<System.TimeSpan> salMAR { get; set; }
        public Nullable<System.TimeSpan> ingMIE { get; set; }
        public Nullable<System.TimeSpan> salMIE { get; set; }
        public Nullable<System.TimeSpan> ingJUE { get; set; }
        public Nullable<System.TimeSpan> salJUE { get; set; }
        public Nullable<System.TimeSpan> ingVIE { get; set; }
        public Nullable<System.TimeSpan> salVIE { get; set; }
        public Nullable<System.TimeSpan> ingSAB { get; set; }
        public Nullable<System.TimeSpan> salSAB { get; set; }
        public Nullable<System.TimeSpan> ingDOM { get; set; }
        public Nullable<System.TimeSpan> salDOM { get; set; }
        public int refriger { get; set; }
        public int tolernc { get; set; }
        public int diaDesc { get; set; }
        public Nullable<System.DateTime> fec_Reg { get; set; }
        public string usu_Reg { get; set; }
        public Nullable<System.DateTime> fec_UltMod { get; set; }
        public string usu_UltMod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Empleado> Tb_Empleado { get; set; }
    }
}
