//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyDreamFoam_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Marcas
    {
        public int codMarc { get; set; }
        public int empleado { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
        public Nullable<int> tipo { get; set; }
        public Nullable<System.DateTime> fec_Reg { get; set; }
        public string usu_Reg { get; set; }
        public Nullable<System.DateTime> fec_UltMod { get; set; }
        public string usu_UltMod { get; set; }
    
        public virtual Tb_Empleado Tb_Empleado { get; set; }
    }
}
