//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyDreamFoam_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_UserSystem
    {
        public int codUser { get; set; }
        public string nomUser { get; set; }
        public string passUser { get; set; }
        public int estdUser { get; set; }
        public Nullable<System.DateTime> fec_Reg { get; set; }
        public string usu_Reg { get; set; }
        public Nullable<System.DateTime> fec_UltMod { get; set; }
        public string usu_UltMod { get; set; }
    }
}
